version: '3.8'

services:
  backend:
    image: backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
    container_name: backend

  frontend:
    image: frontend
    ports:
      - 5000:5000
    container_name: frontend

  redis:
    image: redis:alpine
    container_name: redis

  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    container_name: db